<?php
/**
 * Class was generated by WSDL2PHP tool
 *
 * PHP version 5
 *
 * @category Tools
 * @package  WSDL
 * @author   Andrey Filippov <afi.work@gmail.com>
 * @license  %license%
 * @link     https://solo-framework-lib.googlecode.com
 */

namespace Moneta;

/*REQUIRE_DATATYPES*/

class MonetaWebServiceConnector
{
	/**
	 * Mapping PHP classes and types from a WSDL
	 * Key - type defined in WSDL, value - PHP class name
	 * To avoid conflicts with another classes we have to add prefix for generated data types
	 */
	//private static $classmap = array(/*CLASSMAP*/);

	/**
	 * SoapClient instance
	 *
	 * @var \SoapClient
	 */
	protected $client = null;

	/**
	 * An array of headers to be sent along with the SOAP request
	 *
	 * @var array
	 */
	protected $inputHeaders = null;

	/**
	 * If supplied, this array will be filled with the headers from the SOAP response
	 *
	 * @var array
	 */
	protected $outputHeaders = null;


	/**
	 * Constructor
	 *
	 * @param string $wsdl Path or URL to WSDL file
	 * @param array $options Options like SoapClient->__construct()
	 *
	 * @return \WebServiceConnector
	 */
	function __construct($wsdl, $options = null)
	{
//		foreach(self::$classmap as $key => $value)
//			if(!isset($options["classmap"][$key]))
//				$options["classmap"][$key] = $value;

		if($options === null)
			$options = array();

		$this->client = new \SoapClient($wsdl, $options);
	}

	// Block of generated methods

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\InvoiceRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\InvoiceResponse
	 */
	public function Invoice(\App\Helpers\Moneta\src\Moneta\Types\InvoiceRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\PaymentSystemInfoRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\PaymentSystemInfoResponse
	 */
	public function PaymentSystemInfo(\App\Helpers\Moneta\src\Moneta\Types\PaymentSystemInfoRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\InvoiceBatchRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\InvoiceBatchResponse
	 */
	public function InvoiceBatch(\App\Helpers\Moneta\src\Moneta\Types\InvoiceBatchRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\TransferRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\TransferResponse
	 */
	public function Transfer(\App\Helpers\Moneta\src\Moneta\Types\TransferRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\TransferBatchRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\TransferBatchResponse
	 */
	public function TransferBatch(\App\Helpers\Moneta\src\Moneta\Types\TransferBatchRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\PaymentRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\PaymentResponse
	 */
	public function Payment(\App\Helpers\Moneta\src\Moneta\Types\PaymentRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\PaymentBatchRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\PaymentBatchResponse
	 */
	public function PaymentBatch(\App\Helpers\Moneta\src\Moneta\Types\PaymentBatchRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\AuthoriseTransactionRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\AuthoriseTransactionResponse
	 */
	public function AuthoriseTransaction(\App\Helpers\Moneta\src\Moneta\Types\AuthoriseTransactionRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\AuthoriseTransactionBatchRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\AuthoriseTransactionBatchResponse
	 */
	public function AuthoriseTransactionBatch(\App\Helpers\Moneta\src\Moneta\Types\AuthoriseTransactionBatchRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\ConfirmTransactionRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\ConfirmTransactionResponse
	 */
	public function ConfirmTransaction(\App\Helpers\Moneta\src\Moneta\Types\ConfirmTransactionRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\ConfirmTransactionBatchRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\ConfirmTransactionBatchResponse
	 */
	public function ConfirmTransactionBatch(\App\Helpers\Moneta\src\Moneta\Types\ConfirmTransactionBatchRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\CancelTransactionRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\CancelTransactionResponse
	 */
	public function CancelTransaction(\App\Helpers\Moneta\src\Moneta\Types\CancelTransactionRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\CancelTransactionBatchRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\CancelTransactionBatchResponse
	 */
	public function CancelTransactionBatch(\App\Helpers\Moneta\src\Moneta\Types\CancelTransactionBatchRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\RefundRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\RefundResponse
	 */
	public function Refund(\App\Helpers\Moneta\src\Moneta\Types\RefundRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\ForecastTransactionRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\ForecastTransactionResponse
	 */
	public function ForecastTransaction(\App\Helpers\Moneta\src\Moneta\Types\ForecastTransactionRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\VerifyTransactionRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\VerifyTransactionResponse
	 */
	public function VerifyTransaction(\App\Helpers\Moneta\src\Moneta\Types\VerifyTransactionRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\VerifyTransferRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\VerifyTransferResponse
	 */
	public function VerifyTransfer(\App\Helpers\Moneta\src\Moneta\Types\VerifyTransferRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\VerifyPaymentRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\VerifyPaymentResponse
	 */
	public function VerifyPayment(\App\Helpers\Moneta\src\Moneta\Types\VerifyPaymentRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\VerifyPaymentBatchRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\VerifyPaymentBatchResponse
	 */
	public function VerifyPaymentBatch(\App\Helpers\Moneta\src\Moneta\Types\VerifyPaymentBatchRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\AccountStatementRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\AccountStatementResponse
	 */
	public function AccountStatement(\App\Helpers\Moneta\src\Moneta\Types\AccountStatementRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param long $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\FindAccountByIdResponse
	 */
	public function FindAccountById( $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param string $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\FindAccountByAliasResponse
	 */
	public function FindAccountByAlias( $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\FindAccountsListRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\FindAccountsListResponse
	 */
	public function FindAccountsList(\App\Helpers\Moneta\src\Moneta\Types\FindAccountsListRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\GetAccountPaymentPasswordChallengeRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\GetAccountPaymentPasswordChallengeResponse
	 */
	public function GetAccountPaymentPasswordChallenge(\App\Helpers\Moneta\src\Moneta\Types\GetAccountPaymentPasswordChallengeRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\CreateAccountRequest $request
	 *
	 * @return long
	 */
	public function CreateAccount(\App\Helpers\Moneta\src\Moneta\Types\CreateAccountRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\EditAccountRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\EditAccountResponse
	 */
	public function EditAccount(\App\Helpers\Moneta\src\Moneta\Types\EditAccountRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param long $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\GetOperationDetailsByIdResponse
	 */
	public function GetOperationDetailsById( $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\FindOperationsListByCTIDRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\FindOperationsListByCTIDResponse
	 */
	public function FindOperationsListByCTID(\App\Helpers\Moneta\src\Moneta\Types\FindOperationsListByCTIDRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\FindOperationsListRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\FindOperationsListResponse
	 */
	public function FindOperationsList(\App\Helpers\Moneta\src\Moneta\Types\FindOperationsListRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\FindLastOperationsListRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\FindLastOperationsListResponse
	 */
	public function FindLastOperationsList(\App\Helpers\Moneta\src\Moneta\Types\FindLastOperationsListRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\GetFinancialFlowsListRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\GetFinancialFlowsListResponse
	 */
	public function GetFinancialFlowsList(\App\Helpers\Moneta\src\Moneta\Types\GetFinancialFlowsListRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\GetTurnoverListRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\GetTurnoverListResponse
	 */
	public function GetTurnoverList(\App\Helpers\Moneta\src\Moneta\Types\GetTurnoverListRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param long $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\FindProfileInfoByAccountIdResponse
	 */
	public function FindProfileInfoByAccountId( $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\CreateProfileRequest $request
	 *
	 * @return long
	 */
	public function CreateProfile(\App\Helpers\Moneta\src\Moneta\Types\CreateProfileRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\CheckProfileRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\CheckProfileResponse
	 */
	public function CheckProfile(\App\Helpers\Moneta\src\Moneta\Types\CheckProfileRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\EditProfileRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\EditProfileResponse
	 */
	public function EditProfile(\App\Helpers\Moneta\src\Moneta\Types\EditProfileRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\GetProfileInfoRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\GetProfileInfoResponse
	 */
	public function GetProfileInfo(\App\Helpers\Moneta\src\Moneta\Types\GetProfileInfoRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\FindProfileInfoRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\FindProfileInfoResponse
	 */
	public function FindProfileInfo(\App\Helpers\Moneta\src\Moneta\Types\FindProfileInfoRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\FindContractsRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\FindContractsResponse
	 */
	public function FindContracts(\App\Helpers\Moneta\src\Moneta\Types\FindContractsRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\FindBankAccountsRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\FindBankAccountsResponse
	 */
	public function FindBankAccounts(\App\Helpers\Moneta\src\Moneta\Types\FindBankAccountsRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\CreateBankAccountRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\CreateBankAccountResponse
	 */
	public function CreateBankAccount(\App\Helpers\Moneta\src\Moneta\Types\CreateBankAccountRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\EditBankAccountRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\EditBankAccountResponse
	 */
	public function EditBankAccount(\App\Helpers\Moneta\src\Moneta\Types\EditBankAccountRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\FindLegalInformationRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\FindLegalInformationResponse
	 */
	public function FindLegalInformation(\App\Helpers\Moneta\src\Moneta\Types\FindLegalInformationRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\FindProfileDocumentFilesRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\FindProfileDocumentFilesResponse
	 */
	public function FindProfileDocumentFiles(\App\Helpers\Moneta\src\Moneta\Types\FindProfileDocumentFilesRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\UploadProfileDocumentFileRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\UploadProfileDocumentFileResponse
	 */
	public function UploadProfileDocumentFile(\App\Helpers\Moneta\src\Moneta\Types\UploadProfileDocumentFileRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\FindProfileDocumentsRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\FindProfileDocumentsResponse
	 */
	public function FindProfileDocuments(\App\Helpers\Moneta\src\Moneta\Types\FindProfileDocumentsRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\CreateProfileDocumentRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\CreateProfileDocumentResponse
	 */
	public function CreateProfileDocument(\App\Helpers\Moneta\src\Moneta\Types\CreateProfileDocumentRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\EditProfileDocumentRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\EditProfileDocumentResponse
	 */
	public function EditProfileDocument(\App\Helpers\Moneta\src\Moneta\Types\EditProfileDocumentRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\FindReportsRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\FindReportsResponse
	 */
	public function FindReports(\App\Helpers\Moneta\src\Moneta\Types\FindReportsRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\FindAccountRelationsRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\FindAccountRelationsResponse
	 */
	public function FindAccountRelations(\App\Helpers\Moneta\src\Moneta\Types\FindAccountRelationsRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\GetAccountRelationRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\GetAccountRelationResponse
	 */
	public function GetAccountRelation(\App\Helpers\Moneta\src\Moneta\Types\GetAccountRelationRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\SaveAccountRelationRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\SaveAccountRelationResponse
	 */
	public function SaveAccountRelation(\App\Helpers\Moneta\src\Moneta\Types\SaveAccountRelationRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\DeleteAccountRelationRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\DeleteAccountRelationResponse
	 */
	public function DeleteAccountRelation(\App\Helpers\Moneta\src\Moneta\Types\DeleteAccountRelationRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\GetPersonificationCodeRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\GetPersonificationCodeResponse
	 */
	public function GetPersonificationCode(\App\Helpers\Moneta\src\Moneta\Types\GetPersonificationCodeRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\VerifyPersonificationCodeRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\VerifyPersonificationCodeResponse
	 */
	public function VerifyPersonificationCode(\App\Helpers\Moneta\src\Moneta\Types\VerifyPersonificationCodeRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\ConfirmPersonificationRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\ConfirmPersonificationResponse
	 */
	public function ConfirmPersonification(\App\Helpers\Moneta\src\Moneta\Types\ConfirmPersonificationRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\ApprovePhoneSendConfirmationRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\ApprovePhoneSendConfirmationResponse
	 */
	public function ApprovePhoneSendConfirmation(\App\Helpers\Moneta\src\Moneta\Types\ApprovePhoneSendConfirmationRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\ApprovePhoneApplyCodeRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\ApprovePhoneApplyCodeResponse
	 */
	public function ApprovePhoneApplyCode(\App\Helpers\Moneta\src\Moneta\Types\ApprovePhoneApplyCodeRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\SecureDataRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\SecureDataResponse
	 */
	public function SecureData(\App\Helpers\Moneta\src\Moneta\Types\SecureDataRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\LoginRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\LoginResponse
	 */
	public function Login(\App\Helpers\Moneta\src\Moneta\Types\LoginRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 *
	 *
	 * @param \App\Helpers\Moneta\src\Moneta\Types\LogoutRequest $request
	 *
	 * @return \App\Helpers\Moneta\src\Moneta\Types\LogoutResponse
	 */
	public function Logout(\App\Helpers\Moneta\src\Moneta\Types\LogoutRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	// end of block


	/**
	 * Add header to array of headers to be sent along with the SOAP request.
	 *
	 * @param mixed $header Заголовок
	 *
	 * @return void
	 */
	public function addInputHeader($header)
	{
		$this->inputHeaders[] = $header;
	}

	/**
	 * If supplied, this array will be filled with the headers from the SOAP response
	 *
	 * @return array
	 */
	public function getOutputHeaders()
	{
		return $this->outputHeaders;
	}


	/**
	 * Call method of web-service
	 *
	 * @param string $method Method name
	 * @param mixed $data Data
	 * @param mixed $options Options corresponding like SoapClient->__soapCall()
	 *
	 * @return mixed
	 */
	protected function call($method, $data, $options = null)
	{
		return $this->client->__soapCall($method, $data, $options, $this->inputHeaders, $this->outputHeaders);
	}
}
