<?php

// Warning! This code was generated by WSDL2PHP tool.
// author: Filippov Andrey <afi.work@gmail.com>
// see https://solo-framework-lib.googlecode.com

namespace App\Helpers\Moneta\src\Moneta\Types;

/**
 * Ответ на запрос CancelTransactionRequest.
	 * Response to a transaction cancellation request.
	 *
 */
class CancelTransactionResponse extends CancelTransactionResponseType
{

}
